"""initial schema

Revision ID: 640b01802c05
Revises: 
Create Date: 2026-09-26 14:31:38.774990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '640b01802c05'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('rate_to_base', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'ONLINE', name='fxsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_member_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_member_id', 'alias', name='uq_account_alias_per_member')
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_member_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_member_id', 'month', name='uq_budget_per_month')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('EXACT', 'MERCHANT_NORMALIZED', 'KEYWORD', 'LEARNED', name='ruletype'), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('family_member_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COMMITTED', 'ROLLED_BACK', name='importbatchstatus'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_fingerprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'fingerprint_hash', name='uq_fingerprint_per_account')
    )
    with op.batch_alter_table('file_fingerprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_fingerprints_fingerprint_hash'), ['fingerprint_hash'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('family_member_id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('direction', sa.Enum('DEBIT', 'CREDIT', name='transactiondirection'), nullable=False),
    sa.Column('original_currency', sa.String(length=8), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fx_rate_id', sa.Integer(), nullable=True),
    sa.Column('txn_type', sa.Enum('EXPENSE', 'INCOME', 'TRANSFER', 'REFUND', 'FEE', 'CASH_WITHDRAWAL', 'UNKNOWN', name='transactiontype'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('merchant_sanitized', sa.String(length=120), nullable=True),
    sa.Column('classification_source', sa.Enum('RULE', 'AI', 'MANUAL', 'UNCLASSIFIED', name='classificationsource'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('matched_rule_id', sa.Integer(), nullable=True),
    sa.Column('review_status', sa.Enum('AUTO_APPROVED', 'PENDING', 'APPROVED', 'EXCLUDED', name='reviewstatus'), nullable=False),
    sa.Column('is_transfer', sa.Boolean(), nullable=False),
    sa.Column('linked_transaction_id', sa.Integer(), nullable=True),
    sa.Column('is_probable_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('row_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ),
    sa.ForeignKeyConstraint(['fx_rate_id'], ['fx_rates.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['linked_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['matched_rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_row_fingerprint'), ['row_fingerprint'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_row_fingerprint'))

    op.drop_table('transactions')
    with op.batch_alter_table('file_fingerprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_fingerprints_fingerprint_hash'))

    op.drop_table('file_fingerprints')
    op.drop_table('import_batches')
    op.drop_table('rules')
    op.drop_table('budgets')
    op.drop_table('accounts')
    op.drop_table('fx_rates')
    op.drop_table('family_members')
    op.drop_table('categories')
    # ### end Alembic commands ###
